
use std::sync::{
    atomic::{AtomicU64, Ordering},
    Arc, Mutex,
};

use tokio_stream::wrappers::BroadcastStream;
use tokio_stream::StreamExt;
use tonic::{Request, Response, Status};

use crate::protocol::mini_sync::manager::ChainManager;
use crate::session::table::SessionTable;
use crate::telemetry::event_bus::EventBus;

// Generated by tonic-build from proto/ethscope.proto at compile time
pub mod proto {
    tonic::include_proto!("ethscope");

    // Required for server reflection
    pub const FILE_DESCRIPTOR_SET: &[u8] =
        tonic::include_file_descriptor_set!("ethscope_descriptor");
}

use proto::{
    eth_scope_server::{EthScope, EthScopeServer},
    EmptyRequest, NetworkEvent as ProtoEvent, PeerInfo, PeerListResponse, SummaryResponse,
};

// ─────────────────────────────────────────────────────────────────────────────
// Service struct
// ─────────────────────────────────────────────────────────────────────────────

/// Holds shared references to the live node state.
/// These are the SAME Arc<Mutex<...>> the P2P loops use — no copies.
pub struct EthScopeService {
    chain: Arc<Mutex<ChainManager>>,
    sessions: Arc<Mutex<SessionTable>>,
    event_bus: EventBus,
    canonical_switches: Arc<AtomicU64>,
}

impl EthScopeService {
    pub fn new(
        chain: Arc<Mutex<ChainManager>>,
        sessions: Arc<Mutex<SessionTable>>,
        event_bus: EventBus,
        canonical_switches: Arc<AtomicU64>,
    ) -> Self {
        Self { chain, sessions, event_bus, canonical_switches }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// gRPC method implementations
// ─────────────────────────────────────────────────────────────────────────────

#[tonic::async_trait]
impl EthScope for EthScopeService {
    /// Point-in-time snapshot. Lock taken and immediately released.
    async fn get_summary(
        &self,
        _req: Request<EmptyRequest>,
    ) -> Result<Response<SummaryResponse>, Status> {
        let (canonical_head, sync_height) = {
            let mgr = self.chain.lock().unwrap();
            (mgr.canonical_head_hash(), mgr.canonical_height())
        };

        let active_peers = {
            let st = self.sessions.lock().unwrap();
            st.list_peers().len() as u64
        };

        let canonical_switches = self.canonical_switches.load(Ordering::Relaxed);

        Ok(Response::new(SummaryResponse {
            active_peers,
            discovered_peers: active_peers, // expands with PeerTable later
            canonical_head,
            sync_height,
            canonical_switches,
        }))
    }

    /// All active sessions with their negotiated capabilities.
    async fn list_peers(
        &self,
        _req: Request<EmptyRequest>,
    ) -> Result<Response<PeerListResponse>, Status> {
        let peers = {
            let st = self.sessions.lock().unwrap();
            st.list_peers_full()
        };

        let peer_infos = peers
            .into_iter()
            .map(|(peer_id, agreed_caps)| PeerInfo { peer_id, agreed_caps })
            .collect();

        Ok(Response::new(PeerListResponse { peers: peer_infos }))
    }

    /// Server-streaming live event feed.
    ///
    /// How it works:
    /// 1. Subscribe to EventBus → get broadcast::Receiver
    /// 2. BroadcastStream wraps it into a tokio Stream
    /// 3. Map internal NetworkEvent → proto NetworkEvent
    /// 4. Lagged errors (slow client) are silently skipped, never disconnect
type StreamEventsStream =
    std::pin::Pin<Box<dyn tokio_stream::Stream<Item = Result<ProtoEvent, Status>> + Send>>;

    async fn stream_events(
        &self,
        _req: Request<EmptyRequest>,
    ) -> Result<Response<Self::StreamEventsStream>, Status> {
        let rx = self.event_bus.subscribe();

        let stream = BroadcastStream::new(rx).filter_map(|result| match result {
            Ok(ev) => Some(Ok(ProtoEvent {
                event_type: ev.event_type,
                peer_id: ev.peer_id,
                detail: ev.detail,
                timestamp: ev.timestamp,
            })),
            Err(_lagged) => None, // skip, keep stream alive
        });

        Ok(Response::new(Box::pin(stream)))
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Server bootstrap
// ─────────────────────────────────────────────────────────────────────────────

/// Starts gRPC server on grpc_port. Spawned as a background tokio task.
pub async fn start_grpc_server(
    grpc_port: u16,
    chain: Arc<Mutex<ChainManager>>,
    sessions: Arc<Mutex<SessionTable>>,
    event_bus: EventBus,
    canonical_switches: Arc<AtomicU64>,
) {
    let addr = format!("0.0.0.0:{}", grpc_port)
        .parse()
        .expect("invalid gRPC bind address");

    let svc = EthScopeService::new(chain, sessions, event_bus, canonical_switches);

    // Build reflection service from the file descriptor
    let reflection = tonic_reflection::server::Builder::configure()
        .register_encoded_file_descriptor_set(proto::FILE_DESCRIPTOR_SET)
        .build()
        .unwrap();

    println!("[gRPC] listening on {}", addr);

    tonic::transport::Server::builder()
        .add_service(reflection)
        .add_service(EthScopeServer::new(svc))
        .serve(addr)
        .await
        .expect("gRPC server crashed");
}